version: '2.1'

volumes:
    plant-data:
    dashboard-data:

services:
  dashboard:
    image: balenablocks/dashboard:raspberrypi3
    restart: always
    volumes:
        - 'dashboard-data:/data'
    ports:
        - '80'
  influxdb:
    restart: always
    image: influxdb@sha256:b099bdd1f4306689fd11c02f83b3de7fc11eccd8debf5f345e9be11d0a7cd7dc
    volumes:
      - 'plant-data:/data'
  plantsaver:
    build: ./plantsaver
    privileged: true
    restart: always
    network_mode: host
    labels:
      io.balena.features.balena-api: '1'
  connector:
    image: balenablocks/connector:raspberrypi3
    restart: always
    labels:
      io.balena.features.balena-api: '1' # necessary to discover services
    privileged: true # necessary to change container hostname
  mqtt:
    image: arm32v6/eclipse-mosquitto@sha256:ec3e1dbb9e198ff04d62c2d0f6eff74cad7438c7d080b89a28428fb96c8479c4
    ports:
      - "1883:1883"
    restart: always
