FROM balenalib/%%BALENA_MACHINE_NAME%%-python:latest-bookworm-build

RUN install_packages python3-setuptools python3-pip python3-yaml python3-smbus python3-pil python3-spidev python3-rpi.gpio

RUN pip3 install --upgrade \
  pip \
  setuptools \
  wheel \
  smbus2 \
  RPi.GPIO \
  balena-sdk \
  automationhat \
  paho-mqtt \
  growhat

COPY . /usr/src

CMD python /usr/src/start.py
